/*
-----------------------------------------------------------------------------
A
     __      _   _   _   ______
    |   \   | | | | | | |  ____)                    _
    | |\ \  | | | | | | | |         ___      ___   (_)   ___
    | | \ \ | | | | | | | |____    / _ \   / ___ \  _   / _ \   ___
    | |  \ \| | | | | | |  ____)  | / \ | | |  | | | | | / \ | / _ )
    | |   \ | | | | | | | |_____  | | | | | |__| | | | | | | | | __/
    |_|    \ _| |_| |_| |_______) |_| |_|  \___| | |_| |_| |_| |___|
                                             __/ |                 
                                            \___/   
                                                
                                                
                                                                 F i l e


Copyright: NIIEngine Team Group

Home page: www.niiengine.com 

Email: niiengine@gmail.com OR niiengine@163.com

Licence: commerce(www.niiengine.com/license)(Three kinds)
------------------------------------------------------------------------------
*/

#ifndef __svn_login_dialog__
#define __svn_login_dialog__

/**
@file
Subclass of SvnLoginDialogBase, which is generated by wxFormBuilder.
*/

#include "subversion2_ui.h"

/** Implementing SvnLoginDialogBase */
class SvnLoginDialog : public SvnLoginDialogBase
{
public:
	/** Constructor */
	SvnLoginDialog( wxWindow* parent );

	wxString GetUsername() {return m_textCtrlUsername->GetValue();}
	wxString GetPassword() {return m_textCtrlPassword->GetValue();}
};

#endif // __svn_login_dialog__
