//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: TerminalEmulatorUI.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CODELITE13_0_2_CODELITE_TERMINALEMULATORUI_BASE_CLASSES_H
#define _CODELITE13_0_2_CODELITE_TERMINALEMULATORUI_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/panel.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stc/stc.h>
#include <wx/textctrl.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/dialog.h>
#include <wx/stattext.h>
#include <wx/gauge.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

#include "gsgsPreInclude.h"
// clang-format on

class _gsgsAPI TerminalEmulatorUIBase : public wxPanel
{
protected:
    wxStyledTextCtrl* m_stc;
    wxTextCtrl* m_textCtrl;

protected:
    virtual void OnSendCommand(wxCommandEvent& event) { event.Skip(); }

public:
    wxStyledTextCtrl* GetStc() { return m_stc; }
    wxTextCtrl* GetTextCtrl() { return m_textCtrl; }
    TerminalEmulatorUIBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxTAB_TRAVERSAL);
    virtual ~TerminalEmulatorUIBase();
};


class _gsgsAPI TerminalEmulatorFrameBase : public wxFrame
{
protected:

protected:

public:
    TerminalEmulatorFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Terminal"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxDEFAULT_FRAME_STYLE|wxFRAME_FLOAT_ON_PARENT|wxRESIZE_BORDER);
    virtual ~TerminalEmulatorFrameBase();
};


class _gsgsAPI gsgsProgressDlgBase : public wxDialog
{
protected:
    wxStaticText* m_staticLabel;
    wxGauge* m_gauge;

protected:

public:
    wxStaticText* GetStaticLabel() { return m_staticLabel; }
    wxGauge* GetGauge() { return m_gauge; }
    gsgsProgressDlgBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("gsgs"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(400,-1), long style = wxRESIZE_BORDER);
    virtual ~gsgsProgressDlgBase();
};

#endif
