#include "NodeJSEvents.h"

wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_INTERACT, gsgs::DebugEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_MARK_LINE, gsgs::DebugEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_CONSOLE_LOG, gsgs::DebugEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_EXCEPTION_THROWN, gsgs::DebugEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_UPDATE_BREAKPOINTS_VIEW, gsgs::DebugEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_UPDATE_CONSOLE, gsgs::DebugEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_EVAL_RESULT, clDebugRemoteObjectEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_CREATE_OBJECT, clDebugRemoteObjectEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_OBJECT_PROPERTIES, gsgs::DebugEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_LOCAL_OBJECT_PROPERTIES, gsgs::DebugEvent);

wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_STARTED, gsgs::DebugEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_STOPPED, gsgs::DebugEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_FINISHED, gsgs::DebugEvent);
wxDEFINE_EVENT(wxEVT_NODEJS_DEBUGGER_UPDATE_CALLSTACK, clDebugCallFramesEvent);
