
message(STATUS "正在执行Packaging.cmake脚本")

set(CPACK_PACKAGE_VERSION ${NII_VERSION})
set(CPACK_PACKAGE_VERSION_MAJOR ${NII_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${NII_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${NII_VERSION_PATCH})

set(CPACK_INSTALL_CMAKE_PROJECTS "${NII_BINARY_DIR}" "NII" "ALL" "/")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Graphics Engine")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "NII")
set(CPACK_PACKAGE_NAME "NII")
set(CPACK_PACKAGE_VENDOR "Nii Company")

set(CPACK_RESOURCE_FILE_LICENSE "${NII_SOURCE_DIR}/COPYING")

set(CPACK_PACKAGE_CONTACT "Nii Company")

set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "WriteRegStr \\\${WriteEnvStr_RegKey} \\\"NII_HOME\\\" $INSTDIR")

include(CPack)
