include(NiiFindSource)
macro(get_nii_all_path NII_CMD NII_PATH_FULL_NAME PLATFORM INCLUDE_PATH SOURCE_PATH DEST_INCLUDE_PATH DEST_SOURCE_PATH)
    file(READ ${NII_PATH_FULL_NAME}/${NII_CMD} TEMP_VAR_CONTENTS)
    if(TEMP_VAR_CONTENTS)
        #基本头文件
        get_nii_include(TEMP_VAR_CONTENTS NII_ALL NIITEMPINCLUDE)
        string(COMPARE NOTEQUAL ${NIITEMPINCLUDE} "CMAKENIIERROR" NIITEMPCOMPARE1)
        if(NIITEMPCOMPARE1)       
            string(REPLACE "\n" ";" NIITEMPINCLUDE ${NIITEMPINCLUDE})
            string(REPLACE " " ";" NIITEMPINCLUDE ${NIITEMPINCLUDE})
            foreach(loop_varinclude ${NIITEMPINCLUDE})
                list(APPEND ${INCLUDE_PATH} ${NII_PATH_FULL_NAME}/${loop_varinclude})
                list(APPEND ${DEST_INCLUDE_PATH} ${loop_varinclude})
            endforeach(loop_varinclude)
        endif(NIITEMPCOMPARE1)
        #基本源文件
        get_nii_source(TEMP_VAR_CONTENTS NII_ALL NIITEMPSOURCE)
        string(COMPARE NOTEQUAL ${NIITEMPSOURCE} "CMAKENIIERROR" NIITEMPCOMPARE1)
        if(NIITEMPCOMPARE1)        
            string(REPLACE "\n" ";" NIITEMPSOURCE ${NIITEMPSOURCE})
            string(REPLACE " " ";" NIITEMPSOURCE ${NIITEMPSOURCE})
            foreach(loop_varsource ${NIITEMPSOURCE})
                list(APPEND ${SOURCE_PATH} ${NII_PATH_FULL_NAME}/${loop_varsource})
                list(APPEND ${DEST_SOURCE_PATH} ${loop_varsource})
            endforeach(loop_varsource)
        endif(NIITEMPCOMPARE1)
        #平台头文件
        get_nii_include(TEMP_VAR_CONTENTS ${PLATFORM} NIITEMPINCLUDE)
        string(COMPARE NOTEQUAL ${NIITEMPINCLUDE} "CMAKENIIERROR" NIITEMPCOMPARE1)
        if(NIITEMPCOMPARE1)
            string(REPLACE "\n" ";" NIITEMPINCLUDE ${NIITEMPINCLUDE})
            string(REPLACE " " ";" NIITEMPINCLUDE ${NIITEMPINCLUDE})
            foreach(loop_varinclude ${NIITEMPINCLUDE})
                list(APPEND ${INCLUDE_PATH} ${NII_PATH_FULL_NAME}/${loop_varinclude})
                list(APPEND ${DEST_INCLUDE_PATH} ${loop_varinclude})
            endforeach(loop_varinclude)
        endif(NIITEMPCOMPARE1)
        #平台源文件
        get_nii_source(TEMP_VAR_CONTENTS ${PLATFORM} NIITEMPSOURCE)
        string(COMPARE NOTEQUAL ${NIITEMPSOURCE} "CMAKENIIERROR" NIITEMPCOMPARE1)
        if(NIITEMPCOMPARE1)     
            string(REPLACE "\n" ";" NIITEMPSOURCE ${NIITEMPSOURCE})
            string(REPLACE " " ";" NIITEMPSOURCE ${NIITEMPSOURCE})
            foreach(loop_varsource ${NIITEMPSOURCE})
                list(APPEND ${SOURCE_PATH} ${NII_PATH_FULL_NAME}/${loop_varsource})
                list(APPEND ${DEST_SOURCE_PATH} ${loop_varsource})
            endforeach(loop_varsource)
        endif(NIITEMPCOMPARE1)
        ##################################################################    
        get_nii_spec(TEMP_VAR_CONTENTS NII_Document NIITEMPDoucments)
        string(COMPARE NOTEQUAL ${NIITEMPDoucments} "CMAKENIIERROR" NIITEMPCOMPARE0)
        if(NIITEMPCOMPARE0)
            string(REPLACE "\n" ";" NIITEMPDoucments ${NIITEMPDoucments})
            string(REPLACE " " ";" NIITEMPDoucments ${NIITEMPDoucments})
            foreach(loop_var ${NIITEMPDoucments})           
                set(NII_PATH_FULL_NAME1 "${NII_PATH_FULL_NAME}/${loop_var}")
                get_nii_all_path(${NII_CMD} ${NII_PATH_FULL_NAME1} ${PLATFORM} ${INCLUDE_PATH} ${SOURCE_PATH} ${DEST_INCLUDE_PATH} ${DEST_SOURCE_PATH})
            endforeach(loop_var)       
        endif(NIITEMPCOMPARE0)
        ##################################################################
    endif(TEMP_VAR_CONTENTS)
endmacro(get_nii_all_path)

macro(get_nii_spec_path NII_CMD NII_PATH_FULL_NAME OTHERS OTHER_INCLUDE_PATH OTHER_SOURCE_PATH OTHER_DEST_INCLUDE_PATH OTHER_DEST_SOURCE_PATH)
    file(READ ${NII_PATH_FULL_NAME}/${NII_CMD} TEMP_VAR_CONTENTS)
    if(TEMP_VAR_CONTENTS)
        #平台头文件
        get_nii_include(TEMP_VAR_CONTENTS ${OTHERS} NIITEMPINCLUDE)
        string(COMPARE NOTEQUAL ${NIITEMPINCLUDE} "CMAKENIIERROR" NIITEMPCOMPARE1)
        if(NIITEMPCOMPARE1)
            string(REPLACE "\n" ";" NIITEMPINCLUDE ${NIITEMPINCLUDE})
            string(REPLACE " " ";" NIITEMPINCLUDE ${NIITEMPINCLUDE})
            foreach(loop_varinclude ${NIITEMPINCLUDE})
                list(APPEND ${OTHER_INCLUDE_PATH} ${NII_PATH_FULL_NAME}/${loop_varinclude})
                list(APPEND ${OTHER_DEST_INCLUDE_PATH} ${loop_varinclude})
            endforeach(loop_varinclude)
        endif(NIITEMPCOMPARE1)
        #平台源文件
        get_nii_source(TEMP_VAR_CONTENTS ${OTHERS} NIITEMPSOURCE)
        string(COMPARE NOTEQUAL ${NIITEMPSOURCE} "CMAKENIIERROR" NIITEMPCOMPARE1)
        if(NIITEMPCOMPARE1)     
            string(REPLACE "\n" ";" NIITEMPSOURCE ${NIITEMPSOURCE})
            string(REPLACE " " ";" NIITEMPSOURCE ${NIITEMPSOURCE})
            foreach(loop_varsource ${NIITEMPSOURCE})
                list(APPEND ${OTHER_SOURCE_PATH} ${NII_PATH_FULL_NAME}/${loop_varsource})
                list(APPEND ${OTHER_DEST_SOURCE_PATH} ${loop_varsource})
            endforeach(loop_varsource)
        endif(NIITEMPCOMPARE1)
        ##################################################################    
        get_nii_spec(TEMP_VAR_CONTENTS NII_Document NIITEMPDoucments)
        string(COMPARE NOTEQUAL ${NIITEMPDoucments} "CMAKENIIERROR" NIITEMPCOMPARE0)
        if(NIITEMPCOMPARE0)
            string(REPLACE "\n" ";" NIITEMPDoucments ${NIITEMPDoucments})
            string(REPLACE " " ";" NIITEMPDoucments ${NIITEMPDoucments})
            foreach(loop_var ${NIITEMPDoucments})           
                set(NII_PATH_FULL_NAME1 "${NII_PATH_FULL_NAME}/${loop_var}")
                get_nii_spec_path(${NII_CMD} ${NII_PATH_FULL_NAME1} ${OTHERS} ${OTHER_INCLUDE_PATH} ${OTHER_SOURCE_PATH} ${OTHER_DEST_INCLUDE_PATH} ${OTHER_DEST_SOURCE_PATH})
            endforeach(loop_var)       
        endif(NIITEMPCOMPARE0)
        ##################################################################
    endif(TEMP_VAR_CONTENTS)    
endmacro(get_nii_spec_path)

macro(get_nii_spec_source NII_CMD NII_PATH_FULL_NAME SPEC OUT_PATH DEST_OUT_PATH)
    file(READ ${NII_PATH_FULL_NAME}/${NII_CMD} TEMP_VAR_CONTENTS)
    if(TEMP_VAR_CONTENTS)
        # 指定文件的资源
        get_nii_spec(TEMP_VAR_CONTENTS ${SPEC} NIITEMPINCLUDE)
        string(COMPARE NOTEQUAL ${NIITEMPINCLUDE} "CMAKENIIERROR" NIITEMPCOMPARE1)
        if(NIITEMPCOMPARE1)       
            string(REPLACE "\n" ";" NIITEMPINCLUDE ${NIITEMPINCLUDE})
            string(REPLACE " " ";" NIITEMPINCLUDE ${NIITEMPINCLUDE})
            foreach(loop_varinclude ${NIITEMPINCLUDE})
                list(APPEND ${OUT_PATH} ${NII_PATH_FULL_NAME}/${loop_varinclude})
                list(APPEND ${DEST_OUT_PATH} ${loop_varinclude})
            endforeach(loop_varinclude)
        endif(NIITEMPCOMPARE1)
        ##################################################################    
        get_nii_spec(TEMP_VAR_CONTENTS NII_Document NIITEMPDoucments)
        string(COMPARE NOTEQUAL ${NIITEMPDoucments} "CMAKENIIERROR" NIITEMPCOMPARE0)
        if(NIITEMPCOMPARE0)
            string(REPLACE "\n" ";" NIITEMPDoucments ${NIITEMPDoucments})
            string(REPLACE " " ";" NIITEMPDoucments ${NIITEMPDoucments})
            foreach(loop_var ${NIITEMPDoucments})           
                set(NII_PATH_FULL_NAME1 "${NII_PATH_FULL_NAME}/${loop_var}")
                get_nii_spec_source(${NII_CMD} ${NII_PATH_FULL_NAME1} ${SPEC} ${OUT_PATH} ${DEST_OUT_PATH})
            endforeach(loop_var)       
        endif(NIITEMPCOMPARE0)
        ##################################################################
    endif(TEMP_VAR_CONTENTS)
endmacro(get_nii_spec_source)

macro(get_nii_include_and_source CMD SRCDIR DESTDIR PLATFORM HEADER_FILES SOURCE_FILES RESOURCE_FILES)
    set(SOURCE_FILES "")
    set(HEADER_FILES "")
    set(RESOURCE_FILES "")
    get_nii_all_path(${CMD} ${SRCDIR} ${PLATFORM} ${HEADER_FILES} ${SOURCE_FILES} DEST_HEADER_FILES_TEMP DEST_SOURCE_FILES_TEMP)
    make_directory("${DESTDIR}/include/")   
    foreach(loop_var ${${HEADER_FILES}})
        file(COPY "${loop_var}" DESTINATION "${DESTDIR}/include/")
    endforeach(loop_var)
    set(${HEADER_FILES} "")
    foreach(loop_var ${DEST_HEADER_FILES_TEMP})
        list(APPEND ${HEADER_FILES} ${DESTDIR}/include/${loop_var})
    endforeach(loop_var)
    ######################
    make_directory("${DESTDIR}/src/")
    foreach(loop_var ${${SOURCE_FILES}})
        file(COPY "${loop_var}" DESTINATION "${DESTDIR}/src/")
    endforeach(loop_var)
    set(${SOURCE_FILES} "")
    foreach(loop_var ${DEST_SOURCE_FILES_TEMP})
        list(APPEND ${SOURCE_FILES} ${DESTDIR}/src/${loop_var})
    endforeach(loop_var)
    ######################################添加平台指定资源文件#####################################
    get_nii_spec_source(${CMD} ${SRCDIR} "${PLATFORM}_TARGET_SOURCE" ${RESOURCE_FILES} DEST_RESOURCE_FILES_TEMP)
    make_directory("${DESTDIR}/other/")
    foreach(loop_var ${${RESOURCE_FILES}})
        file(COPY "${loop_var}" DESTINATION "${DESTDIR}/other/")
    endforeach(loop_var)
    set(${RESOURCE_FILES} "")
    foreach(loop_var ${DEST_RESOURCE_FILES_TEMP})
        list(APPEND ${RESOURCE_FILES} ${DESTDIR}/other/${loop_var})
    endforeach(loop_var)
    #用完要清空
    set(DEST_HEADER_FILES_TEMP "")
    set(DEST_SOURCE_FILES_TEMP "")
    set(DEST_RESOURCE_FILES_TEMP "")
endmacro(get_nii_include_and_source)

macro(get_nii_spec_include_and_source CMD SRCDIR DESTDIR OTHERS OTHER_HEADER_FILES OTHER_SOURCE_FILES)
    set(OTHER_HEADER_FILES "")
    set(OTHER_SOURCE_FILES "")
    get_nii_spec_path(${CMD} ${SRCDIR} ${OTHERS} ${OTHER_HEADER_FILES} ${OTHER_SOURCE_FILES} OTHER_DEST_HEADER_FILES_TEMP OTHER_DEST_SOURCE_FILES_TEMP)
    make_directory("${DESTDIR}/include/")   
    foreach(loop_var ${${OTHER_HEADER_FILES}})
        file(COPY "${loop_var}" DESTINATION "${DESTDIR}/include/")
    endforeach(loop_var)
    set(${OTHER_HEADER_FILES} "")
    foreach(loop_var ${OTHER_DEST_HEADER_FILES_TEMP})
        list(APPEND ${OTHER_HEADER_FILES} ${DESTDIR}/include/${loop_var})
    endforeach(loop_var)
    ######################
    make_directory("${DESTDIR}/src/")
    foreach(loop_var ${${OTHER_SOURCE_FILES}})
        file(COPY "${loop_var}" DESTINATION "${DESTDIR}/src/")
    endforeach(loop_var)
    set(${OTHER_SOURCE_FILES} "")
    foreach(loop_var ${OTHER_DEST_SOURCE_FILES_TEMP})
        list(APPEND ${OTHER_SOURCE_FILES} ${DESTDIR}/src/${loop_var})
    endforeach(loop_var)    
    ###############################################################################
    get_nii_spec_source(${CMD} ${SRCDIR} "${OTHERS}_TARGET_SOURCE" OTHER_RESOURCE_FILES_TEMP OTHER_DEST_RESOURCE_FILES_TEMP)
    make_directory("${DESTDIR}/include/")
    foreach(loop_var ${OTHER_RESOURCE_FILES_TEMP})
        file(COPY "${loop_var}" DESTINATION "${DESTDIR}/include/")
    endforeach(loop_var)
    # 用完要清空
    set(OTHER_DEST_HEADER_FILES_TEMP "")
    set(OTHER_DEST_SOURCE_FILES_TEMP "")
    set(OTHER_RESOURCE_FILES_TEMP "")
    set(OTHER_DEST_RESOURCE_FILES_TEMP "")
endmacro(get_nii_spec_include_and_source)
